### ISSUE TITLE
Violet prompt changes color after the first ASIDE asterisk

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#100]
https://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fzcode%2FViolet.zblorb

`sit. open word processor. write. open drawer. get key. unlock cabinet. open it. drink bottle`

Actual: Now everything you type shows up in a red color
Expected: Your typed commands should remain black

![image](https://user-images.githubusercontent.com/96150/144326444-9d2705bb-20f5-40da-9a5c-5badbe55aea9.png)

**Comment by curiousdannii** [comment]
I think in this commit I neglected to handle the situation of character styles returning to normal. It probably just needs to initially clear them before seeing if colours should be applied.

https://github.com/curiousdannii/glkote/commit/40e9b8767b99ae57e3e986b7ecb8be4a6000d85d

**Comment by curiousdannii** [comment]
Fixed in AsyncGlk/testing branch
