### ISSUE TITLE
Forced HTTPS cuts off access to savefiles from the HTTP version

### ISSUE THREAD

**Issue by Hubry** [curiousdannii/parchment#101]
Local storage for http and https are separated, but https on `iplayif.com` was only recently forced, which locked me out of my save files, requiring reaching into the browser's sqlite database files to retrieve them and transplant into the https version.

While the https version seems to have been accessible for a while (the project readme has a link from 1.5 years ago), IFDB's "play online" buttons use http.

**Comment by dfabulich** [comment]
I don't think we can fix that while still redirecting http to https. (I'll update IFDB to point to https, but that's the opposite of what you need.)

**Comment by curiousdannii** [comment]
Ah, sorry about that. I hadn't thought about it when I finally got HTTP->HTTPS redirection working. At least it's only been a week for most people, though some people might have some old Glulx save files from the older version which was also using GlkOte.

**Comment by Hubry** [comment]
At least in my case it was only a single game (a friend showed me Counterfeit Monkey a few weeks ago), but since this repo isn't prominently linked anywhere while you are playing a game, I imagine a number of people lost their saves unexpectedly and didn't report it?

**Comment by curiousdannii** [comment]
In theory I could stop redirecting to HTTPS, then write a lot of code to transfer the savefiles over, but eventually I would want to turn on https redirection again, and there's no guarantee that everyone would have transferred their save files already. It's unfortunate, but I don't think it would really be worth it to try when we don't even know if it would really help that many people.
