### ISSUE TITLE
Parchment just logs an error when you upload an unrecognized story

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#108]
Download https://ifarchive.org/if-archive/games/competition2007/adrift/afdfr/AFDFR.taf go to iplayif.com and click "play a story file on your device."

It's an ADRIFT 4 game, not compatible with Parchment.

Expected: Red error banner, "Error: Unknown storyfile format." That's what you see when you go to https://iplayif.com/?story=https://ifarchive.org/if-archive/games/competition2007/adrift/afdfr/AFDFR.taf

Actual: No red banner; it just logs a `console.error`.

**Comment by curiousdannii** [comment]
Huh, weird. Must have broken it recently, cause I'm sure it used to do that.

**Comment by dfabulich** [comment]
Yeah, I think this was my fault for not adding the catch handler when I implemented file uploading.
