### ISSUE TITLE
Build Parchment as a single HTML file, suitable for downloading

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#114]
Today, Parchment builds as an HTML file with `<script>` tags linking to various required scripts, and a `<link rel=stylesheet>` for its CSS.

If Parchment built a single all-in-one HTML file with all required scripts embedded in it, users would be able to download the HTML file and double-click on it to run it offline, without requiring a complex service worker.

It could even be an optional, secondary download, e.g. `iplayif.com/parchment.html` and then the `index.html` home page could have a link like this: `<a download href=parchment.html>Download Parchment to use it offline</a>`

**Comment by curiousdannii** [comment]
Should be possible, but it's gonna be a big file. With all the engines and all fonts I guess it would be around 10MB. Probably better to zip it up and offer that for download.

**Comment by curiousdannii** [comment]
Turned out to be quite easy! And only 6MB... It's in the testing branch, though because it doesn't handle the loading gif or any fonts yet, I haven't set it to be deployed.

The Iosevka fonts are almost 3MB before being base64 encoded. Do you think it's worth including them in the single file mode? I think it's not.

**Comment by curiousdannii** [comment]
So one option would be to embed only the base font, and rely on the browser faking italics and bold. Here's how that would look.

Real italics and bold:
![Real italics and bold](https://user-images.githubusercontent.com/59074/150877179-13e49752-57ce-4cc8-b457-231699272a6e.png)

Faked italics and bold:
![Screenshot with faked italics and bold](https://user-images.githubusercontent.com/59074/150877121-046df316-c129-448b-b837-90dce10c56fd.png)
