### ISSUE TITLE
AsyncGlk branch: Graphics look blurrier on HiDPI

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#118]
https://curiousdannii.github.io/parchment-testing/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fglulx%2FAlabaster.gblorb

https://iplayif.com/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fglulx%2FAlabaster.gblorb

![image](https://user-images.githubusercontent.com/96150/150874511-74d97e15-df15-48d8-aa2a-a56e3a8bc66e.png)
![image](https://user-images.githubusercontent.com/96150/150874533-22e8b3bf-d84e-4eda-87e3-f54c632a5596.png)

**Comment by curiousdannii** [comment]
Already filed as https://github.com/curiousdannii/asyncglk/issues/10
