### ISSUE TITLE
Allow CSS stylesheet to be passed in the url

### ISSUE THREAD

**Issue by curiousdannii** [curiousdannii/parchment#12]
Custom CSS stylesheet should be able to be loaded by a url parameter

**Comment by PlytonRexus** [comment]
Have we fixed this yet? I might have missed it, but I didn't see any options.

**Comment by curiousdannii** [comment]
No, and to be honest I'm not sure if I want to add it anymore. Browser extensions like Stylish let you change the styles of a webpage. And I've added support for Glk stylehints for those who have a game with particular styles.

**Comment by PlytonRexus** [comment]
Fair enough. Though, I guess this might be useful for people who are embedding iframes on their website?
