### ISSUE TITLE
Publicly document how to use arbitrary URLs

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#120]
https://intfiction.org/t/parchment/54852

It's not very obvious to authors how to make iplayif.com work with arbitrary URLs.

I think the home page of https://iplayif.com/ could stand to have a form (or a link to a form?) where anyone could paste in an URL, and it would redirect the user to `https://iplayif.com/?story=<url>`.

**Comment by zedlopez** [comment]
[demo iplayif url generator](http://zedlopez.org/iplayif.html)

**Comment by dfabulich** [comment]
Make it a PR! https://github.com/curiousdannii/parchment/blob/master/index.html ain't fancy.

**Comment by zedlopez** [comment]
I'll make the change to rewrite the current navbar with the history API and submit a PR tomorrow or soon.
