### ISSUE TITLE
HTTP 302 redirects not being handled

### ISSUE THREAD

**Issue by DavidKinder** [curiousdannii/parchment#122]
IFDB's page for Counterfeit Monkey gives the "Play On-line" link as

https://iplayif.com/?story=https%3A%2F%2Fgithub.com%2Fi7%2Fcounterfeit-monkey%2Freleases%2Fdownload%2Fr10%2FCounterfeitMonkey-10.gblorb

But this doesn't work, at least not for me: with Firefox I get "TypeError: NetworkError when attempting to fetch resource." and with Edge "TypeError: Failed to fetch". The actual link to the Blorb file, https://github.com/i7/counterfeit-monkey/releases/download/r10/CounterfeitMonkey-10.gblorb, works fine in these browsers. However, looking in more detail with wget, accessing this URL returns a HTTP 302 redirect to a URL under "githubusercontent.com". Parchment doesn't seem to be handling that.

**Comment by curiousdannii** [comment]
Huh, we'd already patch it to follow redirects, so I don't know why it's buggy now. Will investigate.

**Comment by curiousdannii** [comment]
Can't reproduce in Firefox 98, Edge 100, or Chrome 99 on Windows.

**Comment by DavidKinder** [comment]
I've now gone round and tested all the computers here (all Windows boxes) - it works on two, and it fails on two. Not clear at all why. I won't complain if you close this issue as I don't know when I'll get a chance to see if I can figure out why this might be happening for me.

**Comment by namekuseijin** [comment]
Link is working fine on Android chrome.

Em ter, 5 de abr de 2022 05:17, David Kinder ***@***.***>
escreveu:
