### ISSUE TITLE
TADS 3 tables, underlining, and font color

### ISSUE THREAD

**Issue by alec-roberts** [curiousdannii/parchment#128]
Though `<b>` and `<i>` tags work well, Parchment doesn't seem to like `<table>`, `<u>`, or `<font color=X>` tags in TADS 3 games.

Here's a little demonstration: https://iplayif.com/?story=https%3A%2F%2Fgithub.com%2Falec-roberts%2Fparchment-test%2Fraw%2Fmain%2Fparchment-test.t3

The TADS source code is here: https://github.com/alec-roberts/parchment-test/blob/main/parchment-test.t

I was hoping for something like this:

![Capture](https://user-images.githubusercontent.com/108770582/177437547-79d31768-51ca-4274-8d25-4ed2d4243865.JPG)

But Parchment yields this:

![Capture](https://user-images.githubusercontent.com/108770582/177437436-9a4877e0-cc21-4d6b-9d51-280882b8961c.JPG)

---

I'm just coming across Parchment (it's awesome! 😄), so I have no idea what challenges there would be to adding these little features. I'd be happy to take a stab at a PR myself if someone points me in the right direction. 😄

**Comment by curiousdannii** [comment]
Hi! So Parchment's TADS engine is a port of the Glk version from [Gargoyle](https://github.com/garglk/garglk). So the first thing to do is check how it runs in Gargoyle.

So true HTML tables won't be happening, that's just not really an option with how Parchment and Glk work. A table that was formatted using a monospaced font might work however. If you need a table that's what I recommend.

Colour support is something I'll be working on in the medium-near future. Underlining might eventually be supported in the medium-far future.

**Comment by curiousdannii** [comment]
No sorry, I've never tried writing anything with TADS. I would've thought that `<tt>` or `<pre>` would work. And they don't work in Gargoyle either?

**Comment by alec-roberts** [comment]
You're correct--they're not working in Gargoyle either. In fact, it looks like it might not even be possible to do something like this in Gargoyle (https://intfiction.org/t/lack-of-html-tag-knowledge/45735). I'll have to poke around a bit more...
