### ISSUE TITLE
Counterfeit Monkey consistently fails to autorestore

### ISSUE THREAD

**Issue by curiousdannii** [curiousdannii/parchment#133]
I feel like some number of months ago CM just didn't attempt to do an autorestore; now it does, but it always fails.

**Comment by cognivore** [comment]
Have you tried switching some letters around?

(I'm very sorry for this dumb joke, I just couldn't resist).

**Comment by nukeop** [comment]
Getting the same error (as I reported in the ticket above)

**Comment by curiousdannii** [comment]
Does the clear autosave button at least work for you?

**Comment by nukeop** [comment]
It deletes the save, but the same problem occurs the next time I try to save.

**Comment by curiousdannii** [comment]
@nukeop You only mean an autosave right, not a manual save? You can still restore those?

**Comment by nukeop** [comment]
Haven't tried saving manually yet, I only tried closing the tab and reopening it.
