### ISSUE TITLE
TADS 2 games can't save/restore

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#138]
A user wrote in to the IFDB support mail reporting an issue with [Unnkulian Underworld: The Unknown Unventure](https://ifdb.org/viewgame?id=tyu4zalevqkvujk4).

https://iplayif.com/?story=https%3A%2F%2Funbox.ifarchive.org%2F%3Furl%3Dhttp%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fadventions%2Fadventions.zip%26open%3Duu1.gam

To repro:

```
GET LAMP
SAVE
RESTORE
```

The game that you saved won't appear on the list of saves to restore.

**Comment by curiousdannii** [comment]
Huh. That's very weird.

**Comment by curiousdannii** [comment]
I can see one issue, which is that when saving it uses the file type "data", and when restoring it uses "save".

Now to determine why it would be doing that...

**Comment by curiousdannii** [comment]
Chris Spiegel has identified the issue, which affects basically all TADS 2 interpreters.

https://github.com/tads-intfic/tads-runner/issues/30

**Comment by curiousdannii** [comment]
Fixed!
