### ISSUE TITLE
Allows margins larger than 25%

### ISSUE THREAD

**Issue by pbienst** [curiousdannii/parchment#147]
When playing fullscreen, 25% margins is a bit too small to be comfortable on my monitor...

**Comment by curiousdannii** [comment]
Duplicate of #36. Though it's not actually a percentage, it's got a max width.

**Comment by pbienst** [comment]
Are you sure this is a duplicate? Full screen works fine, and I was just talking about the margins in the settings menu. They work, but the UI limits setting them to max 25% size. Can't you change the UI so that we can select values larger than 25% there?

**Comment by curiousdannii** [comment]
There is no settings menu, I'm not sure what you're referring to?

**Comment by pbienst** [comment]
Indeed, I submitted a bug report to the wrong project, sorry for wasting your time!
