### ISSUE TITLE
.gitmodules is messed up

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#158]
In https://github.com/curiousdannii/parchment/commit/d636cfd2cef40b3fdafae0efe24cd319da12e537 @curiousdannii updated `.gitmodules` to stop referring to Github URLs, and instead referring to relative file paths:

```
[submodule "src/upstream/asyncglk"]
	path = src/upstream/asyncglk
	url = ../../curiousdannii/asyncglk.git
[submodule "src/upstream/emglken"]
	path = src/upstream/emglken
	url = ../../curiousdannii/emglken.git
[submodule "src/upstream/glkote"]
	path = src/upstream/glkote
	url = ../../curiousdannii/glkote.git
[submodule "src/upstream/ifvms.js"]
	path = src/upstream/ifvms.js
	url = ../../curiousdannii/ifvms.js.git
[submodule "src/upstream/quixe"]
	path = src/upstream/quixe
	url = ../../curiousdannii/quixe.git
```

… that ain't right! Ordinary folks need to use ordinary Github URLs to fetch their submodules.

**Comment by curiousdannii** [comment]
I thought this worked for whichever format of Git URL you used, indeed that's why I changed it! It doesn't work for you? Which is the main Parchment Git URL you're using?

**Comment by dfabulich** [comment]
oh, uh, hey, I guess you're right. I guess #159 screwed up state on my machine; once I hit it, and try to switch back to master, `git submodule update --init --recursive` stops working properly.

**Comment by curiousdannii** [comment]
If you had previously already cloned Parchment it may have got confused when I changed URLs. Sorry for the hassle.

**Comment by curiousdannii** [comment]
I should make the testing branch use the same URLs just in case that helps switch branches.

To be honest, I have two separate checkouts on my computer.

**Comment by curiousdannii** [comment]
Testing now uses relative URLs too.
