### ISSUE TITLE
iplayif.com doesn't work on iOS

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#165]
https://ifdb.org/viewgame?id=op0uw1gn1tjqmjt7

It works fine in Chrome, and even in macOS Safari 18.2, but it doesn't work at all on iOS 18.2.

I've tested on iOS 18.2 on iPhone 13 Pro, and in iOS Simulator iPhone 16 Pro iOS 18.2. The page shows the loading screen and is then just blank.

Safari Dev Tools doesn't say a lot, just this:

```
GiLoad: trying pre-loaded load (array)...
[Error] Viewport argument key "interactive-widget" not recognized and ignored.
	init (main.js:8:2229)
	Oe (main.js:8:21643)
	se (quixe.js:19:8223)
	be (quixe.js:19:4181)
	start (main.js:8:8421)
	(anonymous function) (main.js:14:17887)
```

**Comment by curiousdannii** [comment]
You playing the Glulx demo?

**Comment by dfabulich** [comment]
Sorry, I should have clarified, I'm playing https://iplayif.com/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fzcode%2Fanchor.z8 

When I test `http://localhost:8080/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fzcode%2Fanchor.z8` 
in the `testing` branch in my iOS simulator (revision `db79b6a0b76566c09d7658da6dc2f7f1499d0900`) it works just fine.

**Comment by dfabulich** [comment]
These all fail with a blank screen.

* https://iplayif.com/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fglulx%2FSuperluminal_Vagrant_Twin.gblorb
* https://iplayif.com/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fzcode%2FLostPig.z8
* https://iplayif.com/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fcompetition2017%2FThe%2520Wizard%2520Sniffer%2FThe_Wizard_Sniffer.gblorb

**Comment by curiousdannii** [comment]
Is it trying to use Quixe for all the zcode games?

Anything in the log for the Glulx games?

**Comment by dfabulich** [comment]
Are you able to repro any of this? Is it all working perfectly on your iOS device(s)?

How would I know which engine it's using?

All of the Safari Dev Tools Console logs seem to say the same thing.

**Comment by curiousdannii** [comment]
They're not working on my iOS 17 phone.

That log you copied above has quixe.js in the stack trace.

If it's really using Quixe for Zcode I have no idea what's wrong. But if you copied the log from a Zcode game then I suspect the problem is that it's started throwing errors when you set the interactive-widget viewport meta. But that should also happen for the testing site...

**Comment by dfabulich** [comment]
Here's the log for Lost Pig. I didn't notice that the stacktrace was subtly different. (I guess this isn't Quixe…?)

```
[Error] Viewport argument key "interactive-widget" not recognized and ignored.
	init (main.js:8:2229)
	Oe (main.js:8:21643)
	start (main.js:8:8873)
	(anonymous function) (main.js:14:17887)
```

I suspect that iplayif.com is not running quite exactly what's on my machine on the `testing` branch. Is that plausible? If so, how could we reconcile them?

**Comment by dfabulich** [comment]
Yeah, these are _really_ different.

When I clone db79b6a0b76566c09d7658da6dc2f7f1499d0900 of the `testing` branch and run it in Safari, the `index.html` file refers to `<script src="dist/web/web.js" type="module"></script>`, but iplayif.com refers to `<script src="dist/web/main.js" type="module"></script>`.

https://iplayif.com/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fzcode%2FLostPig.z8 loads `zvm.js` via `file.ts:104`, but http://localhost:8080/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fzcode%2FLostPig.z8 loads `bocfel.js` via `browser.ts:68`.

**Comment by curiousdannii** [comment]
Iplayif.com uses the master branch.

Looks like it is loading the right VM, which would have been inexplicable if it was happening.

I don't know why iOS would now be raising errors when you give it an unknown viewport meta, but at least it should be easy to fix.

**Comment by curiousdannii** [comment]
So it appears no formats are working on iOS (master branch). This must have happened recently, or else someone else would've said something.

However I haven't seen any problems on the testing site. And the viewport meta code wasn't changed. This is very odd.

**Comment by dfabulich** [comment]
I repro this issue in the `master` branch 7e4a939bcf8bfa836d20507b33840f15b2097772 (from Oct 30) and don't repro it in the previous commit `master~1` 678920e1a9c188c1d0266e935d78cfc9be73ce84 (from Oct 12), so the issue is in 7e4a939bcf8bfa836d20507b33840f15b2097772.

7e4a939bcf8bfa836d20507b33840f15b2097772 primarily upgraded from https://github.com/curiousdannii/asyncglk/commit/0b5ba05e34346f9fb4a95d01eb71e5c3e268e4fb (Feb 11) to https://github.com/curiousdannii/asyncglk/commit/08c284061a72f1f74f4dfa5e8ccb79f79661ee59 (Oct 26) so I went into `src/upstream/asyncglk` and did `git checkout 0b5ba05`, and then did `git clean -xdf && npm i && npm start` and found that it was working again.

So I went into `src/upstream/asyncglik` and did a `git bisect` with https://github.com/curiousdannii/asyncglk/commit/0b5ba05e34346f9fb4a95d01eb71e5c3e268e4fb as "good" and https://github.com/curiousdannii/asyncglk/commit/08c284061a72f1f74f4dfa5e8ccb79f79661ee59 as "bad". I found that https://github.com/curiousdannii/asyncglk/commit/08c284061a72f1f74f4dfa5e8ccb79f79661ee59 was itself the bad commit. Its parent commit https://github.com/curiousdannii/asyncglk/commit/dcb9d7f93b8d77e28909aeddcaccc8e4b9b91afc (Oct 25) is good.

So, to sum up, if I start with `master` 7e4a939bcf8bfa836d20507b33840f15b2097772, cd `src/upstream/asyncglk` and `git checkout dcb9d7f` and do a build, it works on iOS.

There's a lot of messing around with the viewport in that commit, so I started digging deeper with Safari Dev Tools. I found that in 7e4a939bcf8bfa836d20507b33840f15b2097772 and on iplayif.com, the `<body>` has a width of 0px. When I uncheck `position: fixed` on it, or add `width: 100vw`, the game content appears on the screen.

https://github.com/curiousdannii/asyncglk/commit/08c284061a72f1f74f4dfa5e8ccb79f79661ee59 says in its commit message:

> Note that the body and html elements need `height: 100%; width: 100%` CSS to be applied.

I'm not sure who you were expecting to do that, but asyncglk eventually did it itself in https://github.com/curiousdannii/asyncglk/commit/8b028d51fbf9dcfe16e9d08dfad9daf097aa7076 (Dec 11).

So the fix would either be for Parchment itself to add CSS in its `master` branch, or to upgrade to a newer version of `asyncglk` (for example by merging the `testing` branch to `master` today).

**Comment by curiousdannii** [comment]
Thank you for the diagnosis! While I feel silly letting that slip by me, it's good to know there isn't a deeper problem. I'll fix this by merging testing into master.

-----------

So the reason why I didn't originally set the `body` styles in AsyncGlk directly is that outside the `#gameport` is meant to be controlled by the larger app. This means that the Parchment for Inform 7 template doesn't include `#gameport` styles, as they depend on which broader website template is used. So strictly speaking it's the responsibility of the app to set those `body` styles. But I decided to just include them in AsyncGlk to be safe. Except it didn't make it into the master branch, whoops!
