### ISSUE TITLE
Something wrong with unicode input and Polish letters

### ISSUE THREAD

**Issue by zajaczkowski** [curiousdannii/parchment#18]
Hi there! I am working on Polish version of Inform 6 library. Everything is working when I use interpreters such as WinFrotz etc. To my great regret, Parchment doesn't want to recognise any Polish letter. Here is Polish version of classic "Ruins": http://iplayif.com/?story=http://zp.lo3.wroc.pl/~gwiazdek/ruins.z5

If I try any verb that doesn't include special character it works fine:
"ob" (short of "obejrzyj" - means "look") returns room description
however:
"weź grzyb" (means "take mushroom") includes character "ź" - and it returns that the verb is not recognised.

I know that you were working on Unicode input long time ago. I read all old discussions, but nothing helped.

Parchment is amazing, but this issue basically inhibits promotion of Polish inform. It would be great if you could help to solve!

Best!

**Comment by curiousdannii** [comment]
@zajaczkowski Could you please upload ruiny.z5 again or attach it here?

**Comment by zajaczkowski** [comment]
Sorry for causing the problem. I needed to take care of some server/domain modifications. I've uploaded the file to my friends server. It will stay stay there for a while...
http://zp.lo3.wroc.pl/~gwiazdek/ruins.z5

I only wonder if this is the right version for testing. You see, the workaround that I use now is small procedure called "GetRidOfPolishLetters". It does as the name suggests, removes polish letters from players input. In result Parchment works as charm, but I'm not really happy about the story file. Now I have to remember to write names of all the objects without polish letters. Same applies to polish verbs. Not so elegant...

Best!

**Comment by zajaczkowski** [comment]
I've just compiled special version of Ruins, in which "GetRidOfPolishLetters" has been turned off. Also there is a verb now that you can use for testing. It is a polish version of "take". You can quickly check that neither "weź grzyb" or "wez grzyb" (meaning 'take mushroom') are not recognized. This is the original bug that caused this discussion. 

Here is the link: http://iplayif.com/?story=http://zp.lo3.wroc.pl/~gwiazdek/ruins_polish_letters.z5

Best!

**Comment by curiousdannii** [comment]
Hi @zajaczkowski I believe I have fixed this now. I am deeply sorry that it took over 3 years to get this fixed!

If you are still interested, I would appreciate you or anyone else checking that it does fix it for more than just the test command of "weź grzyb" which you gave me.

The easiest way to test is is to use [Lectrote](https://github.com/erkyrath/lectrote/releases), and then replace the file resources/app/ifvms/zvm.min.js with this: [zvm.min.js.zip](https://github.com/curiousdannii/parchment/files/1524428/zvm.min.js.zip)

The update will eventually make it into Parchment, but it will take a little time as I am planning a major rewrite of part of Parchment.

**Comment by curiousdannii** [comment]
I pushed the update live. This now works: http://iplayif.com/?story=http://zp.lo3.wroc.pl/~gwiazdek/ruins_polish_letters.z5

Please do let me know if you continue to run into any more trouble! Hopefully next time I will be much quicker to get it all fixed!

**Comment by zajaczkowski** [comment]
Works beautifully! It doesn't matter how long it took! You have just reignited my motivation to continue working on the Polish version of library. I sort of abandoned it...
Thank you! Chapeau bas!

Also, if any Polish speaking person wants to test it, please use the second of the above links:
http://iplayif.com/?story=http://zp.lo3.wroc.pl/~gwiazdek/ruins.z5
