### ISSUE TITLE
zvm - no top bar when accessing saved game url

### ISSUE THREAD

**Issue by roylaza** [curiousdannii/parchment#21]
Hi Guys.

I've written a mapping application that interfaces with Parchment by parsing the top bar to locate the room the player is in.

When using zvm and saving the game (getting the save url), accessing the url again will produce a game without a top bar.

Please see example here:
http://www.zorkmid.co.nr/play/?story=z/ZorkmidDemoGame/ZorkmidDemoGame.z8
By clicking the save button (diskette icon on the top right) and then refreshing the browser you'll be able to see that the top bar has disappeared, consequently the mapping does not work anymore.

Contrast with this url:
http://www.zorkmid.co.nr/play/?story=z/ZorkmidDemoGame/ZorkmidDemoGame.z8&vm=gnusto
(using gnusto) Where doing the above produce the game with the top bar as normal

Thanks

**Comment by curiousdannii** [comment]
@roylaza It should be working now! Please let me know if you run into further trouble.
