### ISSUE TITLE
Not working on Firefox

### ISSUE THREAD

**Issue by Oreolek** [curiousdannii/parchment#22]
My Firefox can't load Parchment on iplayif.com

The console says when trying to get a URL from appspot.com that it (appspot.com server) lacks CORS header ('Access-Control-Allow-Origin') and so it gets blocked.

http://zcode.appspot.com/proxy/?url=http://ifarchive.org/if-archive/games/glulx/Hard_Puzzle.gblorb

**Comment by curiousdannii** [comment]
This doesn't make any sense, because it unconditionally sets the 'Access-Control-Allow-Origin' header to '*'. And when I try it in Firefox I see the header...

Which Firefox version are you using? Does it consistently happen, or could it have been that the server was giving you an error? Does the response get sent correctly or is it a HTTP 500 error or something?

**Comment by Oreolek** [comment]
It's consistent in every Firefox version. I use 43. I see the header too but only in Network section. The blocked call doesn't appear in the Network tab.

**Comment by curiousdannii** [comment]
Neither 42 nor the developer edition 44 have any problems for me...

Maybe an extension could be causing problems? Could you try [it in safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode)?

**Comment by Oreolek** [comment]
Oh, wow, the HTTPS Everywhere extension is the cause.

**Comment by curiousdannii** [comment]
Ah, well now we know the cause. I'll see if I can work around it.

**Comment by curiousdannii** [comment]
I was wondering how I would go about fixing it on the proxy's end, but instead I can just make iplayif.com request https://zcode.appspot.com instead. Easy! I'll do it tomorrow.

**Comment by curiousdannii** [comment]
@Oreolek Can you give it a try now?

**Comment by Oreolek** [comment]
Yep. It works. Thank you!
