### ISSUE TITLE
Contributing styles for the Inform 7 templates

### ISSUE THREAD

**Issue by knownasilya** [curiousdannii/parchment#23]
I want to contribute some style/mobile updates, but am unsure where the relevant styles are. Could you point them out for me? Specifically the index.html and play.html and styles that get generated for inform 7.

**Comment by curiousdannii** [comment]
Parchment doesn't really contribute those styles, except for its own basic formatting. play.html and style.css are part of Inform 7.

It would be good to have more templates available, but I'm not sure where they should be distributed. You should definitely announce them at the [intfiction.org forum](http://www.intfiction.org/forum/) though!

**Comment by knownasilya** [comment]
Thanks. Has there been any mobile work for parchment specifically?

**Comment by curiousdannii** [comment]
The plain Parchment should work fine in mobile browsers. I'm not sure how well the Inform 7 templates work, they could probably be made more responsive.

**Comment by knownasilya** [comment]
I downloaded the latest template from this repo, the one in the readme, seems fine so far. Although it could use some better fonts and less padding.
