### ISSUE TITLE
Building zvm.debug.js?

### ISSUE THREAD

**Issue by juhana** [curiousdannii/parchment#33]
Gruntfile's concat task doesn't have rules to build zvm.debug.js. Is it intentional?

**Comment by curiousdannii** [comment]
Yeah sorry, it's halfway between one build system and another now (although I don't know what the final build system I want will be, maybe using gulp?)

Run `npm run build-zvm` before grunt.

**Comment by juhana** [comment]
Thanks, that works!

**Comment by BroadcastGames** [comment]
I tried with a fresh checkout from github today and it seems to fail for me on same zvm.debug.js

     > browserify src/ifvms.js/src/zvm.js --standalone ZVM > lib/zvm.debug.js

     Error: Cannot find module '/workdir/parchment/src/ifvms.js/src/zvm.js' from '/workdir/parchment'

Should I open a new issue?

**Comment by curiousdannii** [comment]
Probably that means the submodules aren't cloned. Run

```
git submodule init
git submodule update
```

**Comment by BroadcastGames** [comment]
That was it, missing submodules. Thank you.
