### ISSUE TITLE
Text input not recognized in Firefox

### ISSUE THREAD

**Issue by nickbe** [curiousdannii/parchment#34]
the story seems to load correctly but when I enter a command all I receive is:
>That's not a verb I recognise

No matter what I enter.

What am I doing wrong here?

**Comment by curiousdannii** [comment]
@nickbe Can you explain more what you're wanting to do? You shouldn't need to edit index.html, just specify the story url using the ?story url query.

The interpreter is currently have trouble with z3 stories, but z5 should work fine.

If it persistently doesn't work, can you please upload your setup somewhere so I can test it?

**Comment by nickbe** [comment]
Thanks for your effot to help me :)

I have a simple local webserver running on windows. Apache, PHP 5.6. Browser is Firefox.

I'm calling the story with either:
http://localhost/parchment/?story=http://localhost/parchment/stories/curses.z5.js
or by specifying the default story in the script section of the index.html

In the webroot I have the 'lib' and 'stories' folder and the index.html. That's it.
The story seems to load and the intro shows up.

This is the output I get, no matter what I enter:
![screenshot_59](https://cloud.githubusercontent.com/assets/10890765/18726684/de23bd60-8045-11e6-8e7e-bca6642ed488.png)

**Comment by nickbe** [comment]
ok this is really strange. I just tried lurking.z3 from the infocom Lurking Horror game. And this time I can actually enter a command and it's instantly accepted. But it seems strange that the sample stories from the parchment package shouldn't run as well.

**Comment by curiousdannii** [comment]
Okay, I do see the error in Firefox, but not in Chrome. I admit I haven't tested it in Firefox for a little while. I'll track this down now.

**Comment by curiousdannii** [comment]
So turns out this was a bug that was already fixed in ifvms.js, so I just had to update our reference to it. https://github.com/curiousdannii/ifvms.js/pull/21

**Comment by nickbe** [comment]
Great :D 
I'll test it right away

**Comment by nickbe** [comment]
Thanks. Everything works fine now :)
