### ISSUE TITLE
Firefox error when reaching the window bottom

### ISSUE THREAD

**Issue by nickbe** [curiousdannii/parchment#37]
As soon as the text reaches the bottom of the window, it's not possible to type anymore.
The cursor jumps "somewhere", but text input cannot be reached anymore.

**Comment by curiousdannii** [comment]
I can't reproduce this. If you're scrolled up then it won't take input, but if you're scrolled down and the cursor is visible or almost visible then it will scroll the cursor into view and accept text input.

**Comment by nickbe** [comment]
Not here. If I reach the bottom then the input is out of sight

**Comment by curiousdannii** [comment]
I don't really know what you mean sorry. Can you add some screenshots maybe? (Or ideally a video)

**Comment by andrewschultz** [comment]
I'm seeing this problem, too, when I type in a command at the bottom of the window. But if I hit return again, the game text shows.

In fact, pushing any key after pushing return causes the previous move to show, but it seems like it is stuck on first impression.

**Comment by andrewschultz** [comment]
To follow up, I'd like to note that this is a regression from January 20. What I did was to copy the zip file contents to c:\Program Files (x86)\Inform 7\Inform7\Extensions\Reserved\Templates\Parchment then rebuild my z-machine project. With the january 20 zip file it works okay. With the September 23 it does not. I can cut it down further later but I have an IFComp game to finish in the next few days :)

https://github.com/curiousdannii/parchment/commit/3d8cb2fa4295c87bc01ee37c716579830771d18f#diff-9b4398a59f9a215eab27209e62e9ccae

**Comment by curiousdannii** [comment]
@andrewschultz Does it happen with a normal version of Parchment (either the one at iplayif.com or just using index.html), or only with the Inform 7 produced page?

**Comment by andrewschultz** [comment]
@curiousdannii it doesn't happen in my browser when I try to run Zork. It's only with the I7 produced page.

**Comment by nickbe** [comment]
Well it doesn't do the automatic scrolling here. (Latest Firefox - Windows)

Cheers
Nick

Am 26. Sep. 2016, 09:29 +0200 schrieb Andrew Schultz <notifications@github.com>:

**Comment by pteromys** [comment]
I suspect it's the `overflow: hidden;` introduced in 71fc32c4bc0bd8d264c57c9196f611b9221d3756.

Or at least, in a webpage exported from the latest gnome-inform7 (6M62) with parchment from current master, I can get scrolling to look right in a zblorb game if I remove the `overflow: hidden;` and `width: 100%` from `#gameport`.

Do you remember which glulx games and html templates were used to test 71fc32c4bc0bd8d264c57c9196f611b9221d3756? I'd like to see if I can make this work better with zblorbs from gnome-inform7 without breaking the progress made in that commit.

**Comment by curiousdannii** [comment]
This shouldn't be a problem with the new parchment
