### ISSUE TITLE
Command runner? [Question]

### ISSUE THREAD

**Issue by cibersheep** [curiousdannii/parchment#40]
Hi!
I'm working on a qml frontend for Parchment. I'm stuck with command input.
My idea is:
 I have the command typed in a variable: command
 I would like to call the action from a function in this way:
```
   function commandinput(command) {
			runner.toParchment({ type: 'TextInput', code: 'line', input: command });
		}
```
But I'm not able to work it out.

Could anyone help me?

**Comment by curiousdannii** [comment]
[This QML](https://en.wikipedia.org/wiki/QML)? If the interface isn't going to use HTML then don't use Parchment, use the VMs directly:

https://github.com/curiousdannii/ifvms.js
https://github.com/erkyrath/quixe

You would want to use GlkOte to send and receive commands. https://github.com/erkyrath/glkote

**Comment by cibersheep** [comment]
Mm.. interesting. That looks very nice.
I have tried to the jquery and it's not possible because of the window declaration. So, I'm trying to do:
 QML
   vieWeb
     html + js
That works for now. It's a bit dirty but I'm learning.

So, is it possible to do that call to a runner or similar? That would be the last step to have a demo.

**Comment by curiousdannii** [comment]
I don't remember exactly how the old system works sorry, I wrote it several years ago.

toParchment handles output from the VM. If you're trying to send an event back you need to use fromParchment.

**Comment by cibersheep** [comment]
I understand.
Thanks. I'll give it a try.
