### ISSUE TITLE
.min.js version of the latest version of zvm

### ISSUE THREAD

**Issue by twistylittleworkshop** [curiousdannii/parchment#43]
Is there a single minimised file of zvm? There was of the previous version, but it would be good if the new version capable of playing version 3 files was available.

**Comment by curiousdannii** [comment]
Not yet, though it's very easy to minimise the one from ifvms.js. You're right that it would be good for it to be available! Changing Parchment's display layer to use GlkOte instead of the custom one it uses now will still take quite some time.

**Comment by curiousdannii** [comment]
Closing because handled in the ifvms.js issue.
