### ISSUE TITLE
Quixe init: glk_put_jstring: invalid stream

### ISSUE THREAD

**Issue by zachwhalen** [curiousdannii/parchment#44]
Hello,

I get this error message when I try to load a .gblorb game (Everybody Dies, in this case) through iplayif.com:

> Quixe init: glk_put_jstring: invalid stream

E.g. with this URL: 
http://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fcompetition2008%2Fglulx%2Feverybodydies%2FEverybodyDies.gblorb

I suspect this is because of the images in Everybody Dies, since other games are working fine at iplayif.com, but I haven't tested thoroughly. Is this an issue with the game file, or something that could be debugged in Parchment?

The EverybodyDies.gblorb file works fine in desktop interpreters, for what it's worth.

ZW

**Comment by curiousdannii** [comment]
Quixe errors really need to be reported at https://github.com/erkyrath/quixe

The only thing I can do here is update the version of Quixe we use in Parchment. Do you know if it works in the current version of Quixe?

**Comment by zachwhalen** [comment]
Thanks! I didn't realize Quixe was a separate project, so I'll check there and report back if the issue persists in Parchment.

**Comment by zachwhalen** [comment]
FYI it seems that this is related to a bug in the game code and a mismatch between strict and lax error reporting: https://github.com/erkyrath/quixe/issues/28

**Comment by salty-horse** [comment]
@zachwhalen This is fixed now
