### ISSUE TITLE
KeyCharPrimitive() loses window scroll position

### ISSUE THREAD

**Issue by hlabrand** [curiousdannii/parchment#45]
In any game (but for instance my first game http://iplayif.com/?story=http://hlabrande.fr/if/games/espions.z5), when KeyCharPrimitive (in I6) or "wait for any key" (in I7) is used, Parchment loses the position to where the window had been scrolled and send you back to the beginning, instead of staying around the same position.

If a game has a ton of text then a "press any key" and no "clearscreen" instruction, you have to scroll again all the way down to go back to where you were. If the game uses this effect a lot, for example to pace cutscenes, you have to scroll down dozens of time and it's really annoying, borderline unplayable.
(This shows up in games in French, more than in games in English, because the francophone scene uses this effect a lot historically.)

Parchment could either stay at the same position and have the player scroll down a bit to see the text that just popped up, or scroll down automatically as desktop interpreters do.

Thanks! :)

**Comment by curiousdannii** [comment]
I think this is fixed now. Let me know if you have more troubles.
