### ISSUE TITLE
Wrong license file included?

### ISSUE THREAD

**Issue by WalterBarrett** [curiousdannii/parchment#47]
> Most of Parchment is BSD licenced, except for Gunch which is GPL 3.

[The license in the root directory](https://github.com/curiousdannii/parchment/blob/master/LICENCE), however, is the GPLv2.

**Comment by curiousdannii** [comment]
Typo in the readme. It's also called Gnusto, not Gunch!

**Comment by WalterBarrett** [comment]
Hahaha, I was actually wondering what "Gunch" was.

**Comment by curiousdannii** [comment]
[Guncho](http://ifwiki.org/index.php/Guncho) is actually an Interactive Fiction project, but it's not part of Parchment haha.
