### ISSUE TITLE
z8 not working anymore? (Forget, ifarchive down)

### ISSUE THREAD

**Issue by namekuseijin** [curiousdannii/parchment#49]
http://iplayif.com/?story=http://hoosegow.googlecode.com/files/hoosegow16.z8

no luck loading it either from there or from ifarchive.

**Comment by namekuseijin** [comment]
http://iplayif.com/?story=http://www.ifarchive.org/if-archive/games/zcode/Jigsaw.z8

no luck either.  Both give:

An error occurred:
Parchment could not load the story. Check your connection, and that the URL is correct.

**Comment by namekuseijin** [comment]
oh wait.  It seems ifarchive is down... :/

**Comment by jmacdotorg** [comment]
Looks like ifarchive.org was inaccessible for a few minutes. It's up now and the links work as expected for me.

**Comment by namekuseijin** [comment]
LOL, hope you're not hosting IFComp on same server...

still not up here...
