### ISSUE TITLE
Auto-scrolling doesn't work in Chrome

### ISSUE THREAD

**Issue by yandexx** [curiousdannii/parchment#50]
Hi!

None of the games seem to scroll to the bottom correctly whenever new output appears.

For example try this one: http://iplayif.com/?story=http://mirror.ifarchive.org/if-archive/games/zcode/metamorp.z5 Type in "inv" multiple times so it scrolls beyond the bottom of the screen.

I've confirmed this on multiple machines with Chrome 62 and 63 (beta).

I don't know whether it's a bug in Chrome or in Parchment. The auto-scrolling works in Firefox and Edge.

Thanks!

**Comment by curiousdannii** [comment]
You're right, I think this is the same as #45. I forgot this was an outstanding bug. Will try to fix ASAP.

**Comment by yandexx** [comment]
I guess that's solved now.

**Comment by Quuxplusone** [comment]
I see a lack of autoscrolling in Chrome as well. Has this bug recurred?
It sounds like #55 is reporting the same symptom: lack of autoscrolling on Chrome.

Here's my .z8 game — https://quuxplusone.github.io/Advent/play.html also http://iplayif.com/?story=https://quuxplusone.github.io/Advent/advent.z8
Both links seem to work okay in Safari 12.1.2. Both links exhibit the lack-of-autoscrolling bug in Chrome 76.0.3809.132.

I notice that commit 0d2720d has a commit message ("Update parchment.debug.js") that doesn't match what was committed (a one-line edit to structio/input.js).

**Comment by MarcCote** [comment]
@Quuxplusone I made a PR that should hopefully fix that issue.
