### ISSUE TITLE
Link to parchment repository gets in the way of the prompt after continue the play after a Pause the game (mobile)

### ISSUE THREAD

**Issue by rubereaglenest** [curiousdannii/parchment#51]
Hi,

Parchment is really nice for playing IF on mobile, but there's a glitch or problem after passing a "Pause the game". I've tested this on Android. In any zblorb game at the ifcomp site.

After a "Pause the game" or "Press any key", the game continues, but now the link to the parchment repository labeled as "Parchment for Inform 7" is printed just on top of the prompt. It is not a game breaker bug because we can bring the virtual keyboard up hitting any place in the mobile screen, but players usually hit the place where the prompt is, so the link is activated and the navigation jump to this repository, losing all progress in the game.

That is, by default, the mobile view of Parchment do it great hiding that link, but in a somewhat manner, that css trick fails after returning from a Pause or Press any key.

Regards.

**Comment by curiousdannii** [comment]
I can't reproduce this sorry. And because the IF Comp have custom styles it really needs to be reported at https://github.com/iftechfoundation/ifcomp/issues
