### ISSUE TITLE
Switch to https for GA

### ISSUE THREAD

**Issue by curiousdannii** [curiousdannii/parchment#54]
When Parchment is opened over https the browser won't load the GA script, which means my caniuse stats are less accurate.

**Comment by qdacsvx** [comment]
Games don't load for me when opened over https.

https://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fglulx%2FThe_Mary_Jane_of_Tomorrow.gblorb

The story could not be loaded. (http://www.ifarchive.org/if-archive/games/glulx/The_Mary_Jane_of_Tomorrow.gblorb): Error error:

**Comment by curiousdannii** [comment]
Thanks for finding this. I'll update our version of Quixe today.
