### ISSUE TITLE
Parchment for I7 has problems that makes using it uncomfortable for the web

### ISSUE THREAD

**Issue by rubereaglenest** [curiousdannii/parchment#55]
Hi!

In the recent update of my Inform 7 game Tuuli, I've noticed that the template deployed by I7 to play the games in zblorb is not ideal, and even, it has a worst behavior than the pure Parchment experience.

I've released the game as a zblorb because I wanted optimal online play even in mobile. (Quixe is not there yet), but found that the parchment template of Inform 7 has a little problem that makes an abyss for playing online: it does not automatically scroll to the last displayed message.

It would seem a very little problem, but it is a total game breaker in the browser desktop because the player must scroll down by hand every time he types an action, with the mouse wheel or pressing SPACE, every time; once the buffer scroll has disappeared below the browser window. In mobile is just a little annoyance because the user can easily swipe his finger down to read the new text (but still not ideal).

You can test this in my Tuuli release at itchio:

https://rubereaglenest.itch.io/tuuli

Updating the parchment template doesn't help, even it has worsened the problem. You can try, use any game released with the interpreter by I7, and update the interpreter using this file

https://raw.github.com/curiousdannii/parchment/master/lib/parchment-for-inform7.zip

The case is worsened because now the reader can't even scroll down! The new text disappears forever down there and the player simply can't play.

This two cases struck me because plain vanilla Parchment WORKS GREAT AS IS. Compare those experiences with playing my game, or some other, directly from ifplay:

http://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fzcode%2FTuuli.zblorb

Another game so you can test this: Photopia running in a experimental environment:

http://papadasoft.com/par/

And Photopia running from iplayif site:

http://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fzcode%2Fphotopia.z5

So... it would be nice to have this repaired. A parchment for Inform 7 that works exactly equal to the vanilla parchment experience.

Even more, what I really need is web template of vanilla Parchment downloadable from iplayif site, or here. I don't want parchment for I7, I want just a zip with an html and the interpreter that behaves exactly as iplayif.com 

Can we have it?

I know that web development is a tricky thing... this problem is tested in Chrome, When trying to reproduce it in Microsoft EDGE I found that EDGE behaves as intended! The buffer scrolls goes down automatically for new text. YAY!

Ok, now, the parchment update for I7 template is completely broken. It fails as described even in EDGE.

I've not tested the thing in Firefox, and I use Windows 10.

Thanks!

**Comment by curiousdannii** [comment]
I'll try to take a look at this soon.

But as for setting up your own version of Parchment, that's easy. Have a read of https://github.com/curiousdannii/parchment/wiki/Options#parchment_options

**Comment by rubereaglenest** [comment]
Thanks!

I got it!

Now it works fine:

https://rubereaglenest.itch.io/tuuli

Ok. First I tried to build my own release directory, failing in the process, so in the end, I've just pasted my shit into the main parchment-master directory. And it is working! I've deleted some obvious stuff, but I'm pasting the result here to see if I can improve the weigh of the package:

`$ ls -l
total 1780
-rw-r--r-- 1 PC 197121      11 Dec 28 09:56 CNAME
-rw-r--r-- 1 PC 197121     277 Dec 28 09:56 CONTRIBUTORS
-rw-r--r-- 1 PC 197121  171020 Jul  1  2017 Cover.jpg
-rw-r--r-- 1 PC 197121    4316 Dec 28 09:56 Gruntfile.js
-rw-r--r-- 1 PC 197121   17987 Dec 28 09:56 LICENCE
-rw-r--r-- 1 PC 197121 1574603 May  6 17:36 ParchmentTuuli.zip
-rw-r--r-- 1 PC 197121      25 Dec 28 09:56 Procfile
-rw-r--r-- 1 PC 197121    6897 Apr 23 19:33 'Small Cover.jpg'
-rw-r--r-- 1 PC 197121    2691 May  6 17:32 index.html
drwxr-xr-x 1 PC 197121       0 May  6 17:34 lib/
-rw-r--r-- 1 PC 197121     767 Dec 28 09:56 package.json
-rw-r--r-- 1 PC 197121     301 Dec 28 09:56 parchment.manifest
-rw-r--r-- 1 PC 197121     809 May  6 17:27 play_en.html
-rw-r--r-- 1 PC 197121     809 May  6 17:28 play_es.html
drwxr-xr-x 1 PC 197121       0 May  6 17:31 stories/
-rw-r--r-- 1 PC 197121    6854 Apr 23 19:33 style.css
`

Later I realized that I can delete the Quixe interpreter from lib/

The index is a custom launcher with the cover and default style of Inform 7 template, and then, play_en and play_es are proper parchment html with minimal options changes to launch the proper games in stories directory. The style archive is the style of Inform 7 template.

Probably there are already instructions like this out there, but maybe you could add a process for dumb people like me so they could build their own SIMPLE PARCHMENT TEMPLATE.

Thanks!!!

**Comment by lynn** [comment]
I'm also facing this “the player must scroll down by hand every time” problem in a Parchment release of my Inform 7 game. Was a fix ever found?

**Comment by curiousdannii** [comment]
Not yet sorry, I shouldn't have let this take so long. I'll try to get it fixed soon.

**Comment by curiousdannii** [comment]
The Parchment for Inform 7 template has been basically 100% rewritten since this was reported, so it's probably fixed now. If you find more issues though, please make a new bug report.
