### ISSUE TITLE
Color changing not working correctly with bluechairs.z5

### ISSUE THREAD

**Issue by DrMcCoy** [curiousdannii/parchment#56]
See http://iplayif.com/?story=http%3A%2F%2Fwww.ifarchive.org%2Fif-archive%2Fgames%2Fzcode%2Fbluechairs.z5

Type "pay guy" and watch the color changing being awkward in Parchment. In the end, the colors are stuck at black text on black background.

Yeah, the game is weird and possibly misuses something horribly to get this effect.

**Comment by curiousdannii** [comment]
Seems to be working now
