### ISSUE TITLE
Local parchment hangs during loading in Chrome

### ISSUE THREAD

**Issue by averyre** [curiousdannii/parchment#59]
Parchment hangs loading files locally in Chrome while it has no issues doing so with Firefox. This is the same with Phonegap Builds and NW.js.

**Comment by curiousdannii** [comment]
Do you mean trying to load something like `file:///.../parchment/index.html?story=game.z8`? Chrome has restrictions that means that it can only load `.js` files. If you need to load from `file:` I'd recommend you use Inform 7's method of producing a custom Parchment site.
