### ISSUE TITLE
Z3 support

### ISSUE THREAD

**Issue by chrisrochford** [curiousdannii/parchment#64]
When loading Z3 files, receiving the following error:

Uncaught Error: Unsupported Z-Machine version: 3

See: http://iplayif.com/?story=http%3A%2F%2Fwww.batmantis.com%2Fzorks%2Fzork1.z5 (linked from IFDB)

Is support planned for Z3 or has it been deprecated?

**Comment by curiousdannii** [comment]
This is an odd situation. Parchment does support version 3, but it determines which interpreter to use based on the filename. It sees that file is called .z5, so it loads ZVM, which doesn't have support for version 3. The filename should be fixed to reflect the actual version of the game.

**Comment by chrisrochford** [comment]
Ah, got it.  I pulled the story down to local parchment, renamed to z3 and it worked.  I'll ping IFDB to let them know that the hosting site has the wrong filename.  Thanks for the quick suggestion!
