### ISSUE TITLE
Split-screen window generated by scott2zil fails

### ISSUE THREAD

**Issue by jpcompton** [curiousdannii/parchment#70]
ghostking.z5 (attached) generated by Henrik Åsman's [scott2zil](https://github.com/heasm66/scott2zil) appears to break Parchment when it calls for a split screen. The generic splash screen works but when the player hits enter, the screen goes blank. This was observed through the [auto-generated playable link on IFDB](http://iplayif.com/?story=https%3A%2F%2Fgithub.com%2Fheasm66%2Fgames%2Fraw%2Fmaster%2Fcompton%2Fghostking.z5).

The split-screen works fine on multiple flavors of frotz, on Nitfol, and on Lectrote.

(as originally posted at https://intfiction.org/t/parchment-broken-by-split-screen-from-scott2zil/46206/5 )

[ghostking.z5.zip](https://github.com/curiousdannii/parchment/files/4904251/ghostking.z5.zip)

**Comment by curiousdannii** [comment]
Right, this is fixed upstream, I just need to bring the new code into Parchment. Sorry it's taking so long.

**Comment by curiousdannii** [comment]
Finally fixed
