### ISSUE TITLE
SeaMonkey browser detected as IE

### ISSUE THREAD

**Issue by juhana** [curiousdannii/parchment#74]
The latest version of Parchment uses `<script src="dist/web/ie.js" nomodule>` to display an error message about IE not being supported. Since it detects module support and not IE specifically, it's misleading if people use niche browsers like SeaMonkey instead. It could be changed to "doesn't support Internet Explorer and other browsers that lack modern features" or something to that effect.

Original issue here: https://github.com/vorple/borogove-ide/issues/2

**Comment by curiousdannii** [comment]
Yeah that's fair, I'll change the message.

**Comment by curiousdannii** [comment]
Message changed to

>Sorry, but Parchment depends on web features unsupported by this browser. Please try a more modern browser.
