### ISSUE TITLE
iplayif.com downloads the game twice

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#81]
Open https://iplayif.com/?story=https%3A%2F%2Fgithub.com%2Fi7%2Fcounterfeit-monkey%2Freleases%2Fdownload%2Fr10%2FCounterfeitMonkey-10.gblorb in Chrome with dev tools open on the Network tab.

Actual: It downloads the game twice.

First, it downloads 
https://proxy.iplayif.com/proxy/?url=https://github.com/i7/counterfeit-monkey/releases/download/r10/CounterfeitMonkey-10.gblorb 
(that's 11MB)

Then it downloads https://zcode.appspot.com/proxy/?encode=base64&url=https%3A%2F%2Fgithub.com%2Fi7%2Fcounterfeit-monkey%2Freleases%2Fdownload%2Fr10%2FCounterfeitMonkey-10.gblorb
(That's a 14MB base64-encoded version of the same file)

Expected: Download the game at most once. (The base64 proxy is no longer required, right?)

**Comment by curiousdannii** [comment]
I think this is a consequence of how Parchment used to embed Quixe. It won't be a problem with the new Parchment.
