### ISSUE TITLE
Delete and gitignore the `dist` folder

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#92]
The inform7 and web folders are currently checked in as build output. That's weird, and git keeps flagging all of those files as modified whenever I switch branches.

Instead, they should be distributed via Github as Releases (like Lectrote), and the checked-in files should be marked with `.gitignore`.

(I would even recommend rewriting history to remove pasts releases from history, submitting historical releases as Releases on Github; Parchment's `.git` folder is 79MB; it should be 10% that size or less.)

**Comment by curiousdannii** [comment]
I'm using Github Pages. Using Releases wouldn't allow for instant updates.

Probably most of the .git size is from the old-master branch. If you `clone --single-branch` then that would be smaller.

**Comment by curiousdannii** [comment]
Though I guess it could be published through another branch... it's not as simple though. I'll have a think.
