### ISSUE TITLE
Enable sourcemaps for minified JS

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#97]
The build instructions right now recommend disabling the minifier for easier debugging. It would be better if the build generated source maps which we could use instead.

**Comment by curiousdannii** [comment]
I've enabled sourcemaps in the testing branch, so you can try them at https://curiousdannii.github.io/parchment-testing/

What do you think about shipping them in production?

**Comment by dfabulich** [comment]
I'm in favor of shipping them in production.

**Comment by curiousdannii** [comment]
Yes source maps in production is great, it allowed me to instantly find the cause of why the Dialog edit button doesn't work.
